### ISSUE TITLE
The amount of buffered data per connection is unbounded

### ISSUE THREAD

**Issue by ewanas** [magic-wormhole/magic-wormhole-transit-relay#25]
Testing with the websocket protocol, with the receiver paused, the sender was able to transmit 3GB of data to the relay. This might allow for a DoS by using up the memory on the relay.

Implementing a buffer limit per connection would limit the resources used for a single connection and present the sender with an almost accurate view of how much data has not been delivered to the receiver(depending on the buffer size).

Back pressure for the sender could be implemented in case the buffer is full to force the sender to wait for the receiver to catch up.

**Comment by meejah** [comment]
I haven't looked at the code yet, but it would also be useful to confirm if this happens on normal TCP connections or not (or just with the WebSocket flavour).

It would be ideal to let users of the software configure how much to buffer (whether in "messages" or "bytes" .. where "messages" is probably easier to implement / track / understand).

Implementation-wise it's likely we want Twisted producer/consumer to be used properly in the WebSocket connections (and possibly also in plain TCP connections).

**Comment by piegamesde** [comment]
For the TCP version, I know that the differences between sender and receiver progress can be pretty substantial. Of course other network traffic plays a role in there too, but it is way too large nevertheless.

In my opinion, the relay server should not do any buffering except for the obligatory kernel buffers. Also, I don't really see why this should be configurable.

**Comment by meejah** [comment]
The amount will have to be at least "one message" for the WebSocket case since we can't decode less than that.

And yeah ideally it would just essentially pipe straight through but that's .. not really how it works; we have to pull bytes out of the kernel on the one side and push them into the other side. So, that's already "buffering". And the protocol itself "switches modes" after parsing some amount of bytes, which may complicate other approaches.

I don't recall state-of-the-art kernel APIs for this. Conceptually, we essentially want `sendfile` but for sockets. But in any case Twisted would have to support that for this to work in this particular codebase. And such a "direct" approach simply won't work for WebSocket as far as I know: one side can end up doing "masking" and the whole API is just "here's a message" anyway, so we'd need some sort of lower-level support in Autobahn even if Twisted supported some better kernel API). That said, if you have a concrete idea in mind here, I'm all ears :)

(I suggested making it configurable on the assumption we'll have to at least decide "how many bytes shall I pull out at once", approximately, and it seems like a useful knob to turn if you're tuning a higher-capacity relay .. but if that's harder then just hard-coding something reasonable: okay).

**Comment by piegamesde** [comment]
The websocket<->TCP translation is a valid point, I hadn't thought about that. The easiest case then would be to simply read entire messages into a buffer (read 4 bytes, then the rest) at once before forwarding them. (A reasonable maximum message size should be enforced.)

An improvement to that would be to stream the content of the message once the length header is parsed. This would require support from the WebSocket library. In that case the buffer requirement would go down to basically "one additional kernel buffer size".

**Comment by meejah** [comment]
Autobahn gives a WS-API style of "`onMessage()`" so there's no API or support for streaming the bytes of individual websocket messages; the way to tune that would be to play with the message-size (e.g. make it 4KiB or even 1KiB). WebSocket already has max message-sizes, and Autobahn will enforce this.

("A reasonable maximum message size" is exactly the "configurable knob" I head in mind above...since "reasonable" might change depending on your network situation or hardware)

**Comment by meejah** [comment]
(Note, I was wrong about Autobahn it does have access to a "websocket frame" level API allowing streaming of even a single websocket message).

**Comment by vu3rdd** [comment]
It looks like the TCP connection already use the twisted `IPushProducer`/`IConsumer` interfaces that supports some flow control. Saw this comment in the code: https://github.com/magic-wormhole/magic-wormhole-transit-relay/blob/master/src/wormhole_transit_relay/transit_server.py#L105-L110

**Comment by meejah** [comment]
Yeah, I've seen that too ... but I don't find a `registerProducer` call in the code so I'm not sure if/how that actually happens.

With some local Python test-code I don't see backpressure working with WebSockets. I will switch it around to use TCP and see if that's still true or not. (One trick here is to use `removeReader()` to stop Twisted accepting incoming data for a transport .. ).

**Comment by meejah** [comment]
Looks like similar behavior: I can produce 1GiB of data without reading any of it (except the 3 bytes for `ok\n`).

**Comment by meejah** [comment]
Hmmmmm! It seems there _was_ a `registerProducer()` call that was a victim of the refactoring for WebSocket support
