### ISSUE TITLE
TCP vs WebSocket isn't actually "translated"

### ISSUE THREAD

**Issue by meejah** [magic-wormhole/magic-wormhole-transit-relay#28]
The transit relay doesn't actually un-frame incoming TCP messages and turn them into properly-sized WebSocket messages. (Related: the only transit-over-websocket client has a "complimentary" bug whereby it turns the WebSocket stream back into a byte-stream).

The transit _should_ act differently when either side is a different transport protocol. If both sides are the same (i.e. TCP<-->TCP or WebSocket<-->WebSocket), messages can be directly transmitted.

If just one side is TCP, the incoming stream must be buffered until at least one message is available (according to the "first 4 bytes are the size" framing).  Then this message can be sent to the WebSocket side as a single binary WebSocket message (_without_ the 4 byte size).

In the other case, incoming WebSocket messages should have their length prefixed before being streamed to the TCP side. Thus the maximum size of any incoming WebSocket message can be at most `2**32 - 4` (which we can enforce at the WebSocket layer via Autobahn options).

**Comment by piegamesde** [comment]
In a naive implementation this means that the entire message must be buffered in RAM, and this up to twice per open connection. Therefore 4GiB is way too large. The spec already acknowledges this and references the common 64MiB default maximum message size, but without enforcing any values in any way. As a further restriction, the noise protocol has a maximum message size of 64kiB, which will be a hard limit for all protocols using that as cryptography backend.

For handling larger messages, the optimal thing would be to eagerly send partial messages (once you know the length you can in theory already start processing the bytes without buffering the large message), but I don't know of any WebSocket implementations that expose this ability through their API (I mean, why should they, this is an extremely niche use case).

**Comment by piegamesde** [comment]
As an alternative, we can keep the redundant framing bytes for WebSocket, but add the restriction that WebSocket message boundaries must not cross Transit message boundaries. With that, a client implementation might read a message by repeatedly polling WS messages until it has the required number of bytes. Since they are guaranteed to match, it will not have to deal with any leftover buffers for the next message (that's where the complexity comes from, client wise). On the server, this would probably still require peeking into messages in order to inject `flush` as necessary, but apart from that the current logic should still work and the server will not be required to re-frame entire packages.

**Comment by meejah** [comment]
It wouldn't come down to `flush` (we have no control over how TCP is fragmented), but instead the transit would need to read the 4-byte size on incoming TCP streams and make sure to send a WebSocket message at that boundary (for WS clients).

So, _approximately_ the same work as ensuring that a single WS message consists of "a whole message" (with or without the framing bytes). By "approximately" I mean it still needs to understand the framing-bytes (i.e. not just shunt bytes back and forth as now).

**Comment by meejah** [comment]
> For handling larger messages, the optimal thing would be to eagerly send partial messages (once you know the length you can in theory already start processing the bytes without buffering the large message), but I don't know of any WebSocket implementations that expose this ability through their API (I mean, why should they, this is an extremely niche use case).

I don't either; most WebSockets implementations expose an `on-message` and `send-message` API like the Browser standards. We should keep the maximums as big as feasible, letting implementations choose what is good for them (and yeah, Noise imposes its own limits) -- computers get bigger and faster, local conditions may be conducive to big messages, etc.

I personally would choose something fairly small so that a steady stream of websocket messages arrive (quicker, more-granular feedback, better backpressure, etc). In any case, they'll be fragmented to approximately 1500 bytes by TCP. There's going to be buffering going on in many places.

It will take actual testing in plausible network conditions to get the right number, but I'd start with something like 4KiB per websocket message.

**Comment by piegamesde** [comment]
Actually, what we want is already supported by WebSockets itself, RFC 6455 introduces message fragmentation: https://datatracker.ietf.org/doc/html/rfc6455#section-5.4

> The primary purpose of fragmentation is to allow sending a message
   that is of unknown size when the message is started without having to
   buffer that message.  If messages couldn't be fragmented, then an
   endpoint would have to buffer the entire message so its length could
   be counted before the first byte is sent.  With fragmentation, a
   server or intermediary may choose a reasonable size buffer and, when
   the buffer is full, write a fragment to the network.

I think we should try to use that instead of building yet another message fragmentation layer on top of "regular" WS messages.

**Comment by meejah** [comment]
Currently, transit is used to stream a file. So, the sender already has to decide "how big shall I make each message" -- there's no "extra" fragmentation going on (and I'm not proposing to add anything extra).

It's up to them to decide what message size makes sense (up to the limits we have). This will naturally depend on several factors, including available bandwidth, memory, UX, etc.

Although we _could_ use some websocket fragmentation streaming tricks (if available): why?

Certainly in principal there could be protocols interested in messages larger than the current limits but until we have use-cases for that I think we should ignore "how to send a huge message".

**Comment by piegamesde** [comment]
Basically I don't want applications using Transit having to think about their message size, within reasonable limits. You are assuming that all messages over the transit relay are just binary payloads, and yes in those cases it is trivial to control the message size by adjusting the payload buffer size. But I have application protocols that send all their messages, including variable length JSON, over the transit relay. For those, having to split up messages is highly nontrivial.

I did some more research and I think the WS message framing feature not only solves our exact problem, but it should not be too hard to implement.

- Simply enforce that clients split their large messages into multiple frames. Some implementations offer a configuration to do this automatically, others provide an API to send "raw" message frames manually. This is not too hard to implement, and clients are free to not implementing it by simply restricting their message size.
- Client receiving needs no change, as message size is not an issue there.
- The relay server operates on a level of raw message frames instead of WS messages for forwarding. This is a bit more work, but should be doable and is definitely easier than reading partial un-fragmented messages from the stream (that, literally no library provides this and you'd basically have to write your own client). But even this is opt-in, as the server is free to operate on full WS messages, at the cost of higher latency and memory consumption when working with larger messages.

-----

I also propose an alternative solution (it is more fleshed out version of an idea I've written about earlier):

- WS transit messages keep their length prefix as part of the payload
- WS messages are restricted in size. Clients that send larger transit messages need to split them up into multiple WS messages. The first message would contain the length prefix at the beginning of its payload.
- Clients that receive WS messages read the length from the first one, and then await additional messages until they received the expected amount of bytes. This can be realized in a simple loop, because there are guaranteed no bytes left over.
- The transit relay can just forward entire WS messages as is. For the TCP->WS direction, it can split the incoming byte stream into appropriately sized chunks. The only thing that it needs to do is track the beginning of transit messages, to make sure to always start a new WS message on transit message boundaries.

**Comment by meejah** [comment]
> Basically I don't want applications using Transit having to think about their message size, within reasonable limits. 

This is already true. You can send a 4GB message.

**Comment by piegamesde** [comment]
This is true at the moment, but if I understand your proposals correctly this would be changed, since you want to ignore the "large message" use-case.

**Comment by meejah** [comment]
Nothing in this ticket talks about changing any maximums. I've only talked about letting implementations decide what size to use (of course, up to any limits that exist already).

**Comment by piegamesde** [comment]
Okay. But this does not solve the problem that the relay will have to deal with large messages somehow, preferably with fixed memory consumption. (I think that in practice this should never be a problem as most messages are normally sized, but that makes it an easy target for DOS attacks: simply open a dozen connections which send a gigabyte message each)

> And, yes, I want to ignore any use-case for a message bigger than 2**32-4

That we can agree on.

**Comment by meejah** [comment]
Yes, there are many ways to DoS the transit relay but that's only tangentially related to its correct operation wrt. message framing.

For the record, Autobahn does support streaming "a websocket message" one frame at a time (see e.g. https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/interfaces.py#L619 )

**Comment by meejah** [comment]
"rather soon" is vague: we can't do a public release of transit-relay WebSocket support without fixing this behavior.

Size limits is out-of-scope here, that's a resource / DoS issue.

We already have words to this effect in the spec I thought (even if the don't match current behavior)?

**Comment by meejah** [comment]
I think the correct fix here is to split the "relaying" state into two: "translating" or "relaying" (the latter used when both sides are the same, the former used when they're different).

For "relaying" we continue to just funnel bytes (or messages) back and forth.

In "translating" we must buffer until a complete message is received. When bytes come in on WebSocket connections, this is easy (we have "one message" always). On incoming TCP we must buffer.

Having two states allows the outputs to correspond to the correct behavior.

**Comment by piegamesde** [comment]
> On incoming TCP we must buffer.

If the Twisted API supports sending individual WebSocket frames (I think you mentioned that), one can make use of that to reduce the relay side buffering. A compliant WebSocket client implementation should buffer the arriving frames locally and assemble them without any further configuration.

**Comment by meejah** [comment]
We should first do whatever is the simplest way to get correct behavior (I don't know whether that's buffering or sending frames) and can optimize later if required. Either way the implementation will need to split things up locally on incoming TCP data.

**Comment by vu3rdd** [comment]
> In "translating" we must buffer until a complete message is received. When bytes come in on WebSocket connections, this is easy (we have "one message" always). On incoming TCP we must buffer.

I am sure this is thought about, but putting it explicitly here. For the TCP sender to websocket recipient case, there may be a situation where, we have more than one transit length-prefixed-frames in one TCP packet, but it may not be exactly n length-prefixed frames, in which case, the last length-prefixed frame may or may not be complete. We need to buffer them and wait for the next read from the TCP connection to create full transit length-prefixed records before passing them to the websocket leg of the connection. 

Translating from a websocket sender to TCP recipient is much simpler, we just have to prefix length and send them into the TCP connection on the other side of the relay.

**Comment by meejah** [comment]
Yeah .. also worth bearing in mind that Twisted itself is our intermediary between the kernel and `dataReceived()` so there may be multiple "on the wire" TCP packet payloads in a single `dataReceived()` call, I believe.

So, yeah, there could be more than 1 complete message, there could be part of one, the finish of the one we want plus some more, etc. This is why my instincts are that "buffering" (until there's at least one complete message) is going to be the easiest implementation, not frames.

(I do expect all compliant websocket libraries to deal with incoming websocket frames since they can be arbitrarily split up .. but have we confirmed this for the clients we care about?)

**Comment by vu3rdd** [comment]
I have a very rough prototype of the buffering solution. But it still needs a lot of work. I will start putting it in a draft PR.

**Comment by meejah** [comment]
Cool .. I think I had a a brief start on the state-machine splitting, if that helps?

**Comment by meejah** [comment]
We decided to just keep the "redundant" framing
